steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/firstname-studentid/app:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/firstname-studentid/app:$COMMIT_SHA"

options:
  logging: "REGIONAL_USER_OWNED_BUCKET"

substitutions:
  _SERVICE_NAME: "gcp-app"

triggerTemplate:
  projectId: "$PROJECT_ID"
  branchName: "main"
